services:
  - type: web
    name: animehubbot
    runtime: python
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8858714559:AAHO9hh_h8rEc7lMf-RgPxFxMPOzvRYKvnI
      - key: WEBHOOK_URL
        value: https://animehubbot.onrender.com
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: MONGODB_URL
        value: mongodb+srv://saharoveysiii_db_user:g1Duqz5PFN3yCQCL@cluster0.m9p9sfk.mongodb.net/?appName=Cluster0
      - key: ADMINS
        value: 8981470713
      - key: MAIN_CHANNEL
        value: ""
