#!/bin/bash
cat > .env << EOF
BOT_TOKEN=${BOT_TOKEN}
WEBHOOK_URL=${WEBHOOK_URL}
WEBHOOK_SECRET=${WEBHOOK_SECRET}
MONGODB_URL=${MONGODB_URL}
ADMINS=${ADMINS}
MAIN_CHANNEL=${MAIN_CHANNEL:-}
EOF

python main.py
